# Generated by Django 4.2.16 on 2025-11-03 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0004_alter_cryptcurrencyratemodel_currencytype'),
        ('agents', '0002_agentpredictionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentpredictionmodel',
            old_name='agent_name',
            new_name='currency_name',
        ),
        migrations.RemoveField(
            model_name='agentpredictionmodel',
            name='dataset_name',
        ),
        migrations.RemoveField(
            model_name='agentpredictionmodel',
            name='result',
        ),
        migrations.RemoveField(
            model_name='agentpredictionmodel',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='agentpredictionmodel',
            name='accuracy',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='agentpredictionmodel',
            name='actual_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentpredictionmodel',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.datasetupload'),
        ),
        migrations.AddField(
            model_name='agentpredictionmodel',
            name='predicted_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
