# Generated by Django 4.2.16 on 2025-11-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_agent_name_agentpredictionmodel_currency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetupload',
            name='user',
        ),
        migrations.AlterField(
            model_name='agentpredictionmodel',
            name='accuracy',
            field=models.CharField(max_length=50),
        ),
    ]
