# Generated by Django 4.2.16 on 2025-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_datasetupload_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpredictionmodel',
            name='accuracy',
            field=models.FloatField(),
        ),
    ]
