# Generated by Django 4.2.16 on 2025-10-09 10:21

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cryptcurrencyratemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencytype', models.CharField(max_length=100, unique=True)),
                ('doller', models.FloatField()),
                ('rupee', models.FloatField()),
                ('originalprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=admins.models.dataset_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyUpdateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currencyname', models.CharField(max_length=100)),
                ('conversionRate', models.FloatField()),
                ('newCurrencyValue', models.FloatField()),
                ('originalCurrencyValue', models.FloatField()),
                ('chnageValue', models.FloatField()),
                ('profitorloss', models.CharField(max_length=50)),
                ('changedate', models.DateTimeField()),
            ],
            options={
                'db_table': 'currencychnagetable',
                'unique_together': {('currencyname', 'changedate')},
            },
        ),
    ]
