# Generated by Django 4.2.16 on 2025-10-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cryptcurrencyratemodel',
            table='currencyrate',
        ),
    ]
