# Generated by Django 4.2.16 on 2025-10-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_cryptcurrencyratemodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetupload',
            name='file',
            field=models.FileField(upload_to='datasets/'),
        ),
    ]
