# Generated by Django 4.2.16 on 2025-11-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_datasetupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptcurrencyratemodel',
            name='currencytype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
